name: live_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
